/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentRegisterRouteImport } from './routes/student.register'
import { Route as StudentLoginRouteImport } from './routes/student.login'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminTestsIndexRouteImport } from './routes/admin.tests.index'
import { Route as StudentTestTestIdRouteImport } from './routes/student.test.$testId'
import { Route as AdminTestsNewRouteImport } from './routes/admin.tests.new'
import { Route as AdminTestsTestIdResultsRouteImport } from './routes/admin.tests.$testId.results'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentRegisterRoute = StudentRegisterRouteImport.update({
  id: '/student/register',
  path: '/student/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestsIndexRoute = AdminTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentTestTestIdRoute = StudentTestTestIdRouteImport.update({
  id: '/student/test/$testId',
  path: '/student/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestsNewRoute = AdminTestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestsTestIdResultsRoute = AdminTestsTestIdResultsRouteImport.update({
  id: '/tests/$testId/results',
  path: '/tests/$testId/results',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/students': typeof AdminStudentsRoute
  '/student/login': typeof StudentLoginRoute
  '/student/register': typeof StudentRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/tests/new': typeof AdminTestsNewRoute
  '/student/test/$testId': typeof StudentTestTestIdRoute
  '/admin/tests/': typeof AdminTestsIndexRoute
  '/admin/tests/$testId/results': typeof AdminTestsTestIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/login': typeof StudentLoginRoute
  '/student/register': typeof StudentRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/tests/new': typeof AdminTestsNewRoute
  '/student/test/$testId': typeof StudentTestTestIdRoute
  '/admin/tests': typeof AdminTestsIndexRoute
  '/admin/tests/$testId/results': typeof AdminTestsTestIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/students': typeof AdminStudentsRoute
  '/student/login': typeof StudentLoginRoute
  '/student/register': typeof StudentRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/tests/new': typeof AdminTestsNewRoute
  '/student/test/$testId': typeof StudentTestTestIdRoute
  '/admin/tests/': typeof AdminTestsIndexRoute
  '/admin/tests/$testId/results': typeof AdminTestsTestIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/students'
    | '/student/login'
    | '/student/register'
    | '/admin/'
    | '/student/'
    | '/admin/tests/new'
    | '/student/test/$testId'
    | '/admin/tests/'
    | '/admin/tests/$testId/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/students'
    | '/student/login'
    | '/student/register'
    | '/admin'
    | '/student'
    | '/admin/tests/new'
    | '/student/test/$testId'
    | '/admin/tests'
    | '/admin/tests/$testId/results'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/students'
    | '/student/login'
    | '/student/register'
    | '/admin/'
    | '/student/'
    | '/admin/tests/new'
    | '/student/test/$testId'
    | '/admin/tests/'
    | '/admin/tests/$testId/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentLoginRoute: typeof StudentLoginRoute
  StudentRegisterRoute: typeof StudentRegisterRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentTestTestIdRoute: typeof StudentTestTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/register': {
      id: '/student/register'
      path: '/student/register'
      fullPath: '/student/register'
      preLoaderRoute: typeof StudentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tests/': {
      id: '/admin/tests/'
      path: '/tests'
      fullPath: '/admin/tests/'
      preLoaderRoute: typeof AdminTestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/test/$testId': {
      id: '/student/test/$testId'
      path: '/student/test/$testId'
      fullPath: '/student/test/$testId'
      preLoaderRoute: typeof StudentTestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tests/new': {
      id: '/admin/tests/new'
      path: '/tests/new'
      fullPath: '/admin/tests/new'
      preLoaderRoute: typeof AdminTestsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tests/$testId/results': {
      id: '/admin/tests/$testId/results'
      path: '/tests/$testId/results'
      fullPath: '/admin/tests/$testId/results'
      preLoaderRoute: typeof AdminTestsTestIdResultsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTestsNewRoute: typeof AdminTestsNewRoute
  AdminTestsIndexRoute: typeof AdminTestsIndexRoute
  AdminTestsTestIdResultsRoute: typeof AdminTestsTestIdResultsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTestsNewRoute: AdminTestsNewRoute,
  AdminTestsIndexRoute: AdminTestsIndexRoute,
  AdminTestsTestIdResultsRoute: AdminTestsTestIdResultsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentLoginRoute: StudentLoginRoute,
  StudentRegisterRoute: StudentRegisterRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentTestTestIdRoute: StudentTestTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
